DROP TABLE MEMB-ER CASCADE CONSTRAINTS;

CREATE TABLE MEMBER
( ID VARCHAR2(50) 
, PW VARCHAR2(50) NOT NULL
, NAME VARCHAR2(50) NOT NULL
, RRN VARCHAR2(50) NOT NULL
, GENDER VARCHAR2(50) CHECK (GENDER IN ('MEN', 'WOMEN'))
, EMAIL VARCHAR2(50) NOT NULL
, TEL VARCHAR2(50) NOT NULL
, ADDRESS VARCHAR2(50) NOT NULL
, constraint MEMBER_ID_pk primary key(ID)
);

SELECT * FROM MEMBER;


DROP TABLE Board CASCADE CONSTRAINTS;

CREATE TABLE Board
( NUMBER number
, TITLE VARCHAR2(100) NOT NULL
, WRITER VARCHAR2(100) NOT NULL
, CONTENT VARCHAR2(100) NOT NULL
, B_TIME date 
, constraint Board_NUMBER_pk primary key(NUMBER)
);

create sequence num_Board
	start with 1
	increment by 1
	maxvalue 99999
	nocycle
	nocache;
	
SELECT * FROM TB_MEMBER;
INSERT INTO TB_MEMBER VALUES('a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', SYSDATE, 'M');