DROP TABLE MEMBER CASCADE CONSTRAINTS;

CREATE TABLE MEMBER
( ID VARCHAR2(50) PRIMARY KEY
, PW VARCHAR2(50) NOT NULL
, NAME VARCHAR2(50) NOT NULL
, RRN NUMBER(10) NOT NULL
, GENDER VARCHAR2(50) CHECK (GENDER IN ('MEN', 'WOMEN'))
, EMAIL VARCHAR2(50) NOT NULL
, TEL VARCHAR2(50) NOT NULL
, ADDRESS VARCHAR2(50) NOT NULL
);

SELECT * FROM MEMBER;